---
- name: "[OS] 서버 기초 체력 정밀 점검"
  hosts: all
  gather_facts: no
  tasks:
    - name: "1. CPU 모델명 확인"
      shell: "lscpu | grep 'Model name' | awk -F: '{print $2}' | xargs"
      register: cpu_info

    - name: "2. 메모리(Swap) 상태 점검"
      shell: "free -h | grep Swap"
      register: mem_check
      failed_when: mem_check.stdout == ""

    - name: "3. 디스크(/) 사용률 점검"
      shell: "df -h / | awk 'NR==2 {print $5}' | tr -d '%'"
      register: disk_usage
      failed_when: disk_usage.stdout | int >= 80
      ignore_errors: yes

    - name: "4. 외부 네트워크(Google) 통신 점검"
      shell: "ping -c 2 8.8.8.8"
      register: ping_result
      failed_when: "'0% packet loss' not in ping_result.stdout"
      ignore_errors: yes

    - name: "5. 시간 동기화(NTP) 점검"
      shell: "chronyc sources -v"
      register: ntp_check
      failed_when: "'^*' not in ntp_check.stdout"
      ignore_errors: yes

