---
- name: "Redhat OS 점검 및 API 전송"
  hosts: all
  become: no
  gather_facts: yes

  # API 설정 파일 로드 (없어도 기본값 사용)
  pre_tasks:
    - name: Load API config if exists
      include_vars:
        file: ../config/api_config.yml
      failed_when: false
      ignore_errors: yes

  vars:
    # config 파일이 없을 경우 기본값
    api_server:
      url: "{{ api_server.url | default('http://192.168.0.18:8000/api/checks') }}"
      timeout: "{{ api_server.timeout | default(30) }}"
      retry_count: "{{ api_server.retry_count | default(3) }}"

  roles:
    - redhat_check

  # role 실행 후 API 전송
  post_tasks:
    - name: Include API sender tasks
      include_tasks: "{{ playbook_dir }}/../common/roles/api_sender/tasks/main.yml"
      vars:
        check_type: "os"
        checker_name: "강하나"
        check_results: "{{ redhat_check_results }}"


